In [1]:
"""
Repaso de funciones

def nombre(argumentos):
    #bloque de codigo
    return valor

"""

'\nRepaso de funciones\n\ndef nombre(argumentos):\n    #bloque de codigo\n    return valor\n\n'

In [35]:
def sumar(a=1,b=2,c=3):
    """
    Este es un ejemplo de la funcion sumar()
    La fucion sumar permite sumar 3 variables.
    a, b y c
    Los argumentos tienen valores por defecto
    a=1
    b=2
    c=3
    
    Ejemplo
    sumar(10,20,30)
    >>>60
    """
    d = a + b + c
    print(d)

In [30]:
help(sumar)

Help on function sumar in module __main__:

sumar(a=1, b=2, c=3)
    Este es un ejemplo de la funcion sumar()
    La fucion sumar permite sumar 3 variables.
    a, b y c
    Los argumentos tienen valores por defecto
    a=1
    b=2
    c=3
    
    Ejemplo
    sumar(10,20,30)
    >>>60



In [34]:
def ejemplo(*args):
    print(args)
    

In [33]:
sumar(10,20,30,50,60,100,600)

(10, 20, 30, 50, 60, 100, 600)


In [36]:
def ejemplo2(**kwargs):
    print(kwargs)
    

In [37]:
ejemplo2(a=100,apellido="Rodriguez",edad=100)

{'a': 100, 'apellido': 'Rodriguez', 'edad': 100}


In [38]:
ejemplo2(a=100,apellido="Rodriguez",edad=100,sube=501.5)

{'a': 100, 'apellido': 'Rodriguez', 'edad': 100, 'sube': 501.5}


In [39]:
nombre = "Juan"
edad = 50

print("Hola",nombre,"tenes",edad,"años")

Hola Juan tenes 50 años


In [49]:
"""
Construir una función que se llame suma_acotados.
Esta función debe tomar un número arbitrario de
argumentos posicionales y un keyword argument
llamado cota que por defecto debe tener el valor
None. 

Si el argumento cota es None, debe sumar
todos los números, si no debe sumar los números 
que se encuentren entre –cota y cota.

"""

def suma_acotados(*args,cota=None):
    if cota == None:
        suma = 0
        for n in args:
            suma = suma + n
    else:
        modulo = abs(cota)
        suma = 0
        for n in args:
            if n > (-1*modulo) and n<(1*modulo):
                suma = suma + n
    print(suma)

In [56]:
suma_acotados(-10,15,20,cota=16)

5


In [71]:
def sumar(x):
    return x+100

def cuadrado(x):
    return x**2

def dividir(x):
    return x/2


def aplicar(f,conjunto):
    aux = []
    for n in conjunto:
        aux.append(f(n))
    return aux

In [72]:
aplicar(cuadrado,[1,2,3])

[1, 4, 9]

In [73]:
aplicar(dividir,[10,20,30])

[5.0, 10.0, 15.0]

In [74]:
aplicar(sumar,[5,1,2000])

[105, 101, 2100]

In [75]:
"""
Funciones anonimas

lambda x : x**2

def nombre(x):
    return x**2
"""

aplicar(lambda x:x**2,[2,5,10])

[4, 25, 100]

In [77]:
list(map(lambda x:x**2,[2,5,10]))

[4, 25, 100]

In [80]:
precios = [10,40,50,30,200]

dolar =  278

precios_pesos= list(map(lambda x:x*dolar,precios))
precios_pesos

[2780, 11120, 13900, 8340, 55600]

In [81]:
pip install requests

Note: you may need to restart the kernel to use updated packages.


In [83]:
import requests
r = requests.get("https://www.dolarsi.com/api/api.php?type=valoresprincipales")

In [89]:
r.json()[0]["casa"]["venta"]

'277,77'

In [91]:
conda list

# packages in environment at C:\Users\Distancia\anaconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda-client           1.11.2          py310haa95532_0  
anaconda-navigator        2.4.0           py310haa95532_0  
anaconda-project          0.11.1          py310haa95532_0  
anyio                     3.5.0           py310haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py310h2bbff1b_0  
arrow                     1.2.3           py310haa95532_1  
astroid                   2.14.2          py310haa95532_0  
astropy                   5.1             py310h9128911_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     22.1.0          py310haa95532_0  
automat                   20.2.0

In [92]:
r = requests.get("https://www.bna.com.ar/Cotizador/MonedasHistorico")

In [98]:
texto = r.text

In [101]:
dolar = float(texto[539:544])

In [102]:
numeros = [10,20,30]

In [105]:
import numpy as np

In [106]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [114]:
vector[2] = 5

In [116]:
vector*2

array([ 2,  4, 10])

In [122]:
vector = vector * 2

In [123]:
vector

array([ 4,  8, 20])